---
name: checks

on: [push]

jobs:
  Test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Running unittest
        run: |
          python manage.py test
